fireball-packages/inspector

main.js
share/node-header.html

update fireball-x/fireball#485

support add component menu

---

share/comp-section.html

https://github.com/fireball-x/fireball/issues/453

add displayName for component

---

test/renderer/build-node.js
utils/utils.js

update fireball-x/fireball#495

store editor in __editor__ during node building

---

package.json
share/common.css
share/comp-section.html
share/node-header.html
test/fixtures/foobar-inspector.html
test/renderer/basic.js
utils/utils.js

update fireball-x/fireball#495

support custom draw component

---

panel/inspector.js
share/comp-section.html
utils/utils.js

update fireball-x/fireball#487

use uuid for component operation

---

panel/inspector.js

update fireball-x/fireball#459

send undo-commit message when end-editing

---

utils/utils.js

update fireball-x/fireball#677

expand custom properties

---

main.js
panel/inspector.js

fix array size changed report wrong event

---

main.js

update fireball-x/fireball#629

make sure all menu item params been setup

---

main.js

update fireball-x/fireball#629

rename forEach to walk

---

utils/utils.js

update fireball-x/fireball#650

make sure extends can be get

---

utils/utils.js

update fireball-x/fireball#650

use typeID instead

---

panel/inspector.js
share/comp-section.html
test/renderer/normalize-path.js
utils/utils.js

update fireball-x/fireball#586

Support enabled button in component

---

panel/inspector.js
test/renderer/basic.js
test/renderer/demo.js
utils/utils.js

update fireball-x/fireball#817

handle reset-prop event

---

share/image-preview.js

https://github.com/fireball-x/fireball/issues/894

add sprite frame thumbnails to inspector

---

share/comp-section.html

update fireball-x/fireball#875

show enable button by _showTick

---

share/image-preview.js

https://github.com/fireball-x/fireball/issues/894

add sprite frame thumbnails rotate

---

panel/inspector.js

update fireball-x/fireball#1007

show apply messagbox when asset unapplied

---

panel/inspector.js

update fireball-x/fireball#1007

fix unapplied messagebox show many times

---

panel/inspector.js

update fireball-x/fireball#1005

fix meta apply will not replace subMeta array

---

share/comp-section.html
share/node-header.html
share/node.html

update inspector tooltip.
